// قاموس الترجمات الشامل
const translations = {
    en: {
        "header-lang": "🌐 Language",
        "header-auth": "Signin / Signup",
        "header-subtitle": "Linux Enthusiast • Cyber Security Student",
        "nav-about": "About",
        "nav-projects": "Projects",
        "nav-wallpapers": "Wallpapers",
        "nav-github": "GitHub",
        "nav-back-home": "← Back to Home",
        "nav-github-repo": "GitHub Repo",
        
        "about-title": "About Me",
        "about-text": "I am Ahmed (known online as <strong>ahmed-x86</strong> or <strong>ahmedx86</strong>), currently studying Computers and Information Systems. I specialize in Linux systems (Arch Linux is my daily driver) and cybersecurity. I enjoy low-level programming with Assembly, network analysis, and building custom rices using Hyprland and Waybar.",
        
        "projects-title": "My Projects",
        "proj-grub-title": "GRUB Fixer 🛠️",
        "proj-grub-desc": "A universal, automated recovery tool to repair GRUB on UEFI systems with a single command. Part of my Linux system rescue suite.",
        "btn-view-repo": "View Repository",
        
        "proj-asm-title": "ASM Development Environment",
        "proj-asm-desc": "An extension-like setup to run and debug Assembly natively on VS Code and VSCodium for Linux and Windows.",
        
        "proj-hyprland-title": "Hyprland Dotfiles",
        "proj-hyprland-desc": "My personal Hyprland configuration. Focused on productivity, tiling workflow, and a clean, aesthetic Arch Linux setup.",
        
        "proj-ghradar-title": "gh-radar for Waybar",
        "proj-ghradar-desc": "A dynamic and interactive Waybar module that monitors your GitHub activity in real-time with an animated ticker, sound alerts, and avatar notifications.",
        
        "proj-ghheatmap-title": "GitHub Heatmap for Waybar",
        "proj-ghheatmap-desc": "A custom purple widget fetching your 7-day rolling GitHub contributions using the GraphQL API.",
        
        "proj-hijri-title": "Waybar Hijri Calendar",
        "proj-hijri-desc": "A stable Python script for an RTL-fixed, dynamic Hijri calendar in Waybar with zero dependencies.",
        
        "proj-charge-title": "Waybar Mobile Charge Indicator",
        "proj-charge-desc": "A lightweight bash script to show your Android mobile battery status in Waybar via KDE Connect.",
        
        "proj-scripts-title": "Automation Scripts",
        "proj-scripts-desc": "A collection of bash scripts to automate daily tasks and improve the Arch Linux desktop workflow.",
        
        "media-section-title": "Photos & Videos",
        "proj-wallpapers-title": "Wallpapers Gallery",
        "proj-wallpapers-desc": "A curated collection of 4K, minimalist, and aesthetic wallpapers perfectly suited for Linux ricing, Arch Linux, and Hyprland setups.",
        "btn-browse-wallpapers": "Browse Wallpapers",
        
        "proj-gatherings-title": "Linux Gatherings",
        "proj-gatherings-desc": "Explore gatherings, discussions, and events around Linux, open-source software, and cybersecurity.",
        "btn-view-gatherings": "View Linux Gatherings",
        
        "footer-text": "© 2026 Ahmed x86 • Built on Arch Linux ❄️",
        
        "btn-feedback": "Feedback",
        "feedback-title": "Send us your Feedback",
        "feedback-subtitle": "We value your opinion (kinda).",
        "feedback-name-placeholder": "Your Name",
        "feedback-email-placeholder": "Your Email",
        "feedback-desc-placeholder": "Describe your issue...",
        "feedback-submit": "Submit Feedback",
        
        "lang-modal-title": "Select Language",
        "lang-modal-subtitle": "Choose website language",
        "btn-copy": "Copy",

        // === ASM Page Translations (EN) ===
        "asm-page-title": "Ahmed x86 - Assembly Development Environment 🚀",
        "asm-page-desc": "An all-in-one repository designed to kickstart your Assembly (ASM) development.",
        "asm-intro-text": "This environment provides out-of-the-box support for Linux x64 and Windows (x86/x64), featuring pre-configured VS Code settings for a seamless workflow.",
        "asm-quick-install": "🛠️ Quick Installation",
        "asm-choose-weapon": "Choose your weapon (Operating System) and run the corresponding command to configure your environment immediately:",
        "asm-linux-install": "🐧 Linux (One-Line Installer)",
        "asm-linux-desc": "Supports Arch, Debian/Ubuntu, Fedora, Alpine, openSUSE, Solus, Gentoo, Puppy Linux, and Void.",
        "asm-win10-install": "🪟 Windows 10 / 11 (PowerShell Installer)",
        "asm-win10-desc": "Optimized for modern Windows environments.",
        "asm-win7-install": "🏛️ Windows 7 (Legacy Support)",
        "asm-win7-desc": "Dedicated script for Windows 7 compatibility.",
        "asm-key-features": "✨ Key Features",
        "asm-feat-1": "<strong>Dual-Platform Support:</strong> Native installers for both Windows and Linux, ensuring your dev environment is consistent everywhere.",
        "asm-feat-2": "<strong>VS Code Integration:</strong> Pre-configured <code>tasks.json</code> and <code>launch.json</code> allow you to build and debug your code with a single shortcut (<code>Ctrl+Shift+B</code>).",
        "asm-feat-3": "<strong>Global CLI Tool:</strong> Installs the custom <code>asm-run</code> command globally, allowing you to compile and test <code>.asm</code> files directly from any terminal without opening an editor.",
        "asm-feat-4": "<strong>Smart Dependency Management:</strong> Automatically detects your package manager on Linux and skips unnecessary downloads, while natively setting up NASM on Windows.",
        "asm-feat-5": "<strong>Legacy Support:</strong> Special installer for <strong>Windows 7</strong> to ensure assembly development isnt limited by OS version.",
        "asm-feat-6": "<strong>Cross-Compilation:</strong> Ready-to-use toolchains to compile and test Windows binaries directly from Linux using Wine and MinGW.",
        "asm-smart-engine": "🧠 Smart Engine Features",
        "asm-smart-1": "<strong>Bulletproof Execution:</strong> Features built-in network stability checks, strict input validation loops, and a <code>Ctrl+C</code> trap that automatically cleans up partial downloads.",
        "asm-smart-2": "<strong>Security First:</strong> Implements rigorous <strong>SHA256 Integrity Checks</strong> for external binaries to guarantee file authenticity.",
        "asm-smart-3": "<strong>Editor Agnostic:</strong> Automatically scans and detects your installed IDE (VS Code, VSCodium, Cursor) and sets up Assembly extensions.",
        "asm-smart-4": "<strong>Universal Package Tracking:</strong> Detects if your editor is installed via Native Package Manager, Snap, or Flatpak and configures extensions isolatedly.",
        "asm-smart-5": "<strong>Auto-Path Patching:</strong> Dynamically updates <code>launch.json</code> and <code>tasks.json</code> based on your current OS username and directory path.",
        "asm-final-note-title": "🎭 Final Note",
        "asm-important-note": "<strong>[!IMPORTANT]</strong><br>This project was built to prove that \"Understanding Linux\" isn't about talking, it's about building solutions that work on <strong>9+ distributions</strong> with a single click.",
        "asm-stay-hard": "Stay Hard, Keep Coding. 🚀",
        "asm-arch-note": "<strong>Note for Arch Users:</strong> Because \"I use Arch btw\" shouldn't mean spending three hours on config. We've got you covered. 😎",
        
        // === gh-radar Page Translations (EN) ===
        "ghradar-page-title": "Ahmed x86 - gh-radar for Waybar 📡",
        "ghradar-page-desc": "A dynamic and interactive Waybar module that monitors your GitHub activity in real-time.",
        "ghradar-demo-caption": "Watch gh-radar's animated ticker and notifications in action!",
        "ghradar-features-title": "✨ Key Features",
        "ghradar-feat-1": "<strong>Animated Ticker:</strong> Waybar text changes dynamically when a new push occurs. It shows the branch and commit message, then the repository name, and finally returns to your username.",
        "ghradar-feat-2": "<strong>Audio Alerts:</strong> Plays a retro notification sound instantly upon detecting a new push.",
        "ghradar-feat-3": "<strong>Avatar Notifications:</strong> Sends a native desktop notification containing the committer's actual GitHub avatar and commit details.",
        "ghradar-feat-4": "<strong>Interactive Buttons:</strong> Left-click to open your GitHub profile, Right-click to open notifications directly from Waybar.",
        "ghradar-feat-5": "<strong>Manual Refresh (New!):</strong> Middle-click the module to instantly fetch the latest updates using Linux signals (<code>SIGUSR1</code>).",
        "ghradar-feat-6": "<strong>Smart Resource Management:</strong> Dynamic polling intervals (10s when active, 60s when idle) or a complete Sleep Mode (<code>-t 0</code>) to save battery and bandwidth.",
        "ghradar-feat-7": "<strong>Custom Icons (New!):</strong> Choose from 10 different Nerd Font icons (Octocat, Git branch, etc.) using the <code>-icon</code> argument.",
        "ghradar-feat-8": "<strong>API Optimized:</strong> Uses GitHub's <code>ETag</code> headers to respect API rate limits.",
        "ghradar-install-title": "🛠️ Installation & Setup",
        "ghradar-install-step1": "1. Clone & Copy Files",
        "ghradar-install-step2": "2. Add Your Credentials (.env)",
        "ghradar-env-desc1": "Create a <code>.env</code> file to authenticate with GitHub:",
        "ghradar-env-desc2": "Add the following (replace with your info):",
        "ghradar-install-step3": "3. Install Dependencies",
        "ghradar-dep-desc": "Depending on your Linux distribution, install the required Python libraries. You also need an audio player (<code>mpv</code> or <code>paplay</code>) and a notification daemon (<code>libnotify</code>).",
        "ghradar-dep-arch": "For Arch Linux / Manjaro:",
        "ghradar-dep-ubuntu": "For Ubuntu / Debian (or using pip):",
        "ghradar-usage-title": "⚙️ Usage & Arguments",
        "ghradar-usage-desc": "The script supports arguments to customize its behavior:",
        "ghradar-usage-arg1": "<code>my_repos_only</code>: Only triggers alerts for repositories you own (ignores activity from other repos you watch/star).",
        "ghradar-usage-arg2": "<code>-t 0</code>: <strong>Manual Mode</strong>. The script will not poll GitHub automatically. It will sleep completely until you middle-click the Waybar module.",
        "ghradar-usage-arg3": "<code>-icon &lt;1-10&gt;</code>: <strong>(New!)</strong> Choose the icon displayed in Waybar. Choose a number from 1 to 10 (e.g., <code>-icon 2</code> for the Octocat).",
        "ghradar-waybar-title": "🖥️ Waybar Configuration",
        "ghradar-waybar-step1": "1. Module Configuration (<code>config.jsonc</code>)",
        "ghradar-pro-tip": "💡 Pro Tip:",
        "ghradar-pro-tip-desc": "Add <code>\"reload_style_on_change\": true,</code> at the very top of your Waybar config file. This allows Waybar to instantly apply changes when you edit the config or style files without needing a manual restart!",
        "ghradar-waybar-desc1": "Add this module to your Waybar config file (under <code>modules-left</code>, <code>modules-center</code>, or <code>modules-right</code>):",
        "ghradar-waybar-desc2": "<em>(Note: Change <code>ahmed-x86</code> to your actual GitHub username in the <code>on-click</code> URL).</em>",
        "ghradar-waybar-step2": "2. Styling (<code>style.css</code>)",
        "ghradar-style-desc": "Choose the theme that matches your current Waybar setup and add it to your <code>style.css</code>.",
        "ghradar-style-1": "1. Default (GitHub Dark)",
        "ghradar-style-2": "2. Catppuccin (Mocha)",
        "ghradar-style-3": "3. Dracula",
        "ghradar-restart-note": "<strong>Restart Waybar:</strong> Apply the changes by restarting Waybar using <code>killall waybar && waybar & disown</code> (Only needed if you haven't enabled <code>reload_style_on_change</code>).",
        "ghradar-btn-repo": "View GitHub Repository",

        // === GRUB Fixer Page Translations (EN) ===
        "grub-page-title": "Ahmed x86 - GRUB Fixer 🛠️",
        "grub-page-desc": "Automated, secure Universal (UEFI & Legacy BIOS) bootloader rescue suite with Zero-Interaction CLI Flags, Deep Scan Intelligence, and Kernel Environment Detection.",
        "grub-about-title": "About the Project",
        "grub-about-desc": "<b>GRUB Fixer (V18 - The \"Zero-Interaction\" Automation Update)</b> takes system recovery to the absolute limit. It is an automated, bulletproof Bash script designed to repair the GRUB bootloader on both <b>UEFI and Legacy BIOS</b> systems. <b>V18</b> introduces <b>CLI Flags for fully automated, headless deployments</b>, building upon the proactive <b>Deep Scan Engine</b> and <b>Kernel Command Line Detection</b> introduced in V17 to eliminate decision fatigue during system recovery.",
        "grub-v18-note": "<strong>🚀 New in V18:</strong> The script now features <b>Headless Automation via CLI Flags</b>! Pass <code>-env l -auto</code> to bypass all confirmation prompts and let the script fix GRUB silently in seconds based on auto-detection.",
        "grub-flags-title": "🚩 V18 CLI Flags Reference",
        "grub-flags-desc": "V18 introduces Command-Line Arguments to bypass prompts and enable headless automation:",
        "grub-flag-1": "<strong><code>-env l</code> or <code>-env live</code>:</strong> Force the script to assume a <b>Live Environment</b> (USB/ISO).",
        "grub-flag-2": "<strong><code>-env h</code> or <code>-env host</code>:</strong> Force the script to assume a <b>Real Machine / Host</b> environment.",
        "grub-flag-3": "<strong><code>-auto</code>:</strong> The \"Ultimate Mode\" flag. Bypasses all confirmation prompts <code>(y/n)</code>, automatically assumes default mount points, and executes the repair instantly.",
        "grub-flag-4": "<strong><code>--version</code> or <code>-v</code>:</strong> Print the current version and exit.",
        "grub-intel-title": "✨ The Intelligence Update (V17 & V18)",
        "grub-intel-1": "<strong>Headless Automation (V18):</strong> Pass flags directly via the pipeline to execute complex repairs without a single keystroke.",
        "grub-intel-2": "<strong>Kernel Cmdline Detection (V17):</strong> Analyzes <code>/proc/cmdline</code> to instantly distinguish between Live ISOs (Archiso, Casper, etc.) and real installed systems.",
        "grub-intel-3": "<strong>Deep Scan Engine (V17):</strong> Stealthily scans and mounts partitions in read-only mode to locate <code>fstab</code> and resolve UUIDs/PARTUUIDs before user interaction.",
        "grub-intel-4": "<strong>Unified One-Click Prompt (V17):</strong> Combines environment detection and layout confirmation into a single, clean summary.",
        "grub-evo-title": "⚙️ Evolution History (V16 - V12)",
        "grub-evo-1": "<strong>In-Situ (Local) Mode Detection (V16):</strong> Intelligently detects if run from the installed OS, bypassing the chroot environment to repair GRUB locally in seconds.",
        "grub-evo-2": "<strong>Dynamic UEFI 32-bit Detection (V15):</strong> Detects rare 32-bit UEFI architectures and automatically switches the GRUB target to <code>i386-efi</code>.",
        "grub-evo-3": "<strong>Dynamic Execution Timer (V14):</strong> Delivers gamer-style human status messages based on repair speed.",
        "grub-evo-4": "<strong>OS Prober Integration (V13):</strong> Automatically enables <code>GRUB_DISABLE_OS_PROBER=false</code> to ensure Windows/other distros are detected.",
        "grub-evo-5": "<strong>Legacy BIOS & Smart Target Disk Extraction (V12):</strong> Full support for <code>i386-pc</code> with intelligent parent disk extraction.",
        "grub-core-title": "🧠 Core \"Power User\" Features",
        "grub-core-1": "<strong>Zero-Interaction FSTAB Parsing:</strong> Resolves <code>UUID</code> and <code>PARTUUID</code> tags instantly, mapping Btrfs subvolumes without manual input.",
        "grub-core-2": "<strong>3-Tier Fallback System:</strong> Gracefully falls back from Pro Mode (FSTAB) to Smart Auto-Detection, and finally to Manual Input.",
        "grub-core-3": "<strong>Bulletproof Btrfs Loop:</strong> Interactive validation for complex subvolume hierarchies (<code>@</code>, <code>@home</code>, <code>@log</code>).",
        "grub-core-4": "<strong>VM & NVRAM Rescue:</strong> Forced <code>--removable</code> flag usage for stubborn UEFI firmware and QEMU/KVM environments.",
        "grub-usage-title": "🛠️ Usage",
        "grub-usage-desc": "Run the \"Ultimate Rescue Weapon\" directly from your terminal:",
        "grub-usage-opt1-title": "Option 1: Quick One-Liner (Interactive Mode)",
        "grub-usage-opt1-desc": "The classic, smart, and unified interactive experience:",
        "grub-usage-opt2-title": "Option 2: Fully Automated (Zero-Interaction Mode) 💥",
        "grub-usage-opt2-desc": "Skip all questions and let the script fix GRUB silently based on auto-detection (perfect for Live USBs):",
        "grub-usage-opt3-title": "Option 3: Manual Download",
        "grub-version-title": "📜 Version History",
        "grub-version-summary": "Click to view full version history",
        "grub-th-version": "Version",
        "grub-th-changes": "Major Changes",
        "grub-v1": "Initial manual chroot logic.",
        "grub-v2": "Input validation and device checks.",
        "grub-v3": "Automatic <code>/mnt</code> cleanup (umount -R).",
        "grub-v4": "Failsafe mode, OS detection, and EOF automation.",
        "grub-v5": "VM/NVRAM Rescue and TTY Pipeline support.",
        "grub-v6": "Smart Auto-Detection & UX Proposal Flow.",
        "grub-v7": "Dynamic Custom Volumes Support (The Rescue Update).",
        "grub-v8": "Smart EFI Validation, Logging & Root Checks (Smart & Secure Update).",
        "grub-v9": "Dynamic Btrfs subvolumes support with smart routing.",
        "grub-v10": "Dynamic EFI Mount Logic, Forced Validation Loop, and Improved Auto-Detection.",
        "grub-v11": "Zero-Interaction Mode (fstab parser), 3-Tier Fallback System.",
        "grub-v12": "Added Legacy BIOS (i386-pc) support, auto-detection, and Target Disk extraction.",
        "grub-v13": "Added OS Prober support to automatically detect dual-boot systems (e.g., Windows).",
        "grub-v14": "Added Dynamic Execution Timer with gamer-style human responses (The Speedrun Update).",
        "grub-v15": "Added Universal UEFI Support (32-bit/i386-efi) with dynamic bitness detection.",
        "grub-v16": "Added In-Situ (Local) Mode to repair GRUB directly from the running system without Live USB/chroot.",
        "grub-v17": "Deep Scan Engine, Kernel Cmdline Detection, & Unified UX Prompt.",
        "grub-v18": "<b>Current:</b> Added CLI Flags (--version, -env l/h, -auto) for complete Zero-Interaction Automation.",
        "grub-req-title": "📋 System Requirements",
        "grub-req-1": "<strong>Environment:</strong> Live Linux USB (Arch, CachyOS, etc.) OR Local Installed OS.",
        "grub-req-2": "<strong>Architecture:</strong> UEFI (x86_64/i386) or Legacy BIOS (i386-pc).",
        "grub-req-3": "<strong>Privileges:</strong> Sudo/Root access required.",
        "grub-warn-title": "⚠️ Disclaimer",
        "grub-warn-desc": "Always verify the <b>Deep Scan</b> summary before confirming the repair process, especially on dual-boot systems.",
        "grub-warn-v19": "<strong>⚠️ Planned for V19:</strong> Researching automated <b>LUKS Encryption</b> support for seamless encrypted partition repair.",
        "grub-btn-star": "⭐ Star on GitHub",
        "grub-footer-text": "© 2026 Ahmed x86 • Part of the Linux System Recovery Suite ❄️",

        // === Hyprland Dotfiles Page Translations (EN) ===
        "hypr-page-title": "🍙 Ahmed x86 - Hyprland Dotfiles",
        "hypr-page-desc": "A minimal, highly customized, and functional Hyprland setup on Arch Linux.",
        "hypr-about-title": "About",
        "hypr-about-desc1": "Welcome to my personal <b>Hyprland</b> configuration. Designed for aesthetics and performance using the Catppuccin color palette.",
        "hypr-about-desc2": "<b>The Ecosystem Experience:</b> Features a seamless, interactive automated setup to integrate your GitHub account (Rolling Contributions & Radar) and your Mobile device (via KDE Connect).",
        "hypr-software-title": "Software & Tools",
        "hypr-waybar-title": "Waybar Modules",
        "hypr-mod-left": "Left Modules",
        "hypr-mod-l1": "Power Menu (wlogout)",
        "hypr-mod-l2": "GitHub Activity",
        "hypr-mod-l3": "GitHub Radar",
        "hypr-mod-l4": "Workspace Switcher",
        "hypr-mod-l5": "Idle Inhibitor",
        "hypr-mod-l6": "System Updates",
        "hypr-mod-center": "Center Modules",
        "hypr-mod-c1": "Color Picker",
        "hypr-mod-c2": "Hijri Calendar",
        "hypr-mod-c3": "Clock",
        "hypr-mod-c4": "Privacy Dots",
        "hypr-mod-c5": "System Tray",
        "hypr-mod-right": "Right Modules",
        "hypr-mod-r1": "Media Controls",
        "hypr-mod-r2": "Keyboard Layout",
        "hypr-mod-r3": "Bluetooth & Network",
        "hypr-mod-r4": "Battery & Power Profiles",
        "hypr-mod-r5": "Volume & Mic",
        "hypr-mod-r6": "Notification Toggle",
        "hypr-install-title": "Installation",
        "hypr-install-online": "Online Install (Fastest & Fully Automated)",
        "hypr-install-offline": "Offline Install (Manual)",
        "hypr-gallery-title": "Gallery",
        "hypr-btn-repo": "View GitHub Repository",

        // === Arch Sessions Page Translations (EN) ===
        "arch-page-title": "Ahmed x86 - Linux Sessions 🖥️",
        "arch-page-desc": "Explore the Kingdom of Linux with recorded sessions that teach you everything from installation to advanced terminal mastery.",
        "arch-sessions-title": "Recorded Sessions",
        "arch-sessions-desc": "Simple, practical sessions that guide you to proficiency in Linux. Click on any video thumbnail to start watching.",
        "arch-zorin-title": "Zorin OS Installation Guide",
        "arch-zorin-desc": "A comprehensive, step-by-step tutorial on how to install Zorin OS from scratch. Perfect for a smooth and visually stunning Linux experience.",
        "arch-cmds-title": "Essential Linux Commands: Advanced Guide",
        "arch-cmds-desc": "Take your terminal skills to the next level. This session provides an advanced, in-depth explanation of the most important basic Linux commands and how to master them.",
        "pagination-prev": "« Prev",
        "pagination-next": "Next »",

        // === Mobile Charge Indicator Page Translations (EN) ===
        "mob-page-title": "Ahmed x86 - Mobile Charge Indicator for Waybar 📱",
        "mob-page-desc": "A lightweight bash script that shows your phone battery in Waybar using KDE Connect.",
        "mob-about-title": "About",
        "mob-about-desc": "A sleek and lightweight script that displays your mobile phone battery status directly in <b>Waybar</b> using <b>KDE Connect</b>. Perfect for Hyprland and Sway users.",
        "mob-features-title": "Features",
        "mob-feat-1": "Auto detection of connected phone ID",
        "mob-feat-2": "Dynamic battery colors (Normal / Warning / Critical)",
        "mob-feat-3": "Charging indicator icon",
        "mob-feat-4": "Click module to ping your phone",
        "mob-install-title": "Installation",
        "mob-install-desc1": "Run the following commands in your terminal to install the script:",
        "mob-install-desc2": "The script will automatically copy <b>mobile.sh</b> to:",
        "mob-waybar-conf-title": "Waybar Configuration",
        "mob-waybar-style-title": "Waybar Style",
        "mob-btn-repo": "View GitHub Repository",

        // === GitHub Heatmap Page Translations (EN) ===
        "heatmap-page-title": "Ahmed x86 - GitHub Rolling Contributions 🟪",
        "heatmap-page-desc": "A dynamic, 7-day rolling GitHub heatmap with a custom purple theme for your status bar.",
        "heatmap-about-title": "About",
        "heatmap-about-desc": "A terminal or bar integration script that fetches your <b>GitHub contribution activity for the last 7 rolling days</b> using the GitHub GraphQL API and renders a custom purple colored heatmap (■) with detailed tooltips. Designed for seamless integration with status bars like <b>Waybar</b>, <b>Polybar</b>, or any custom desktop widget.",
        "heatmap-note": "<strong>💡 Note:</strong> This is a modified fork of <a href='https://github.com/ad1822/weekly-github-waybar-module' target='_blank'>ad1822's module</a>. It has been rewritten to display a <b>rolling 7-day window</b> (avoiding empty trackers at the start of the week) and features a custom <b>purple color scheme</b>.",
        "heatmap-features-title": "✨ Key Features",
        "heatmap-feat-1": "<strong>Real-Time Data:</strong> Pulls contribution data directly from GitHub's GraphQL API.",
        "heatmap-feat-2": "<strong>Rolling 7-Day Window:</strong> Always shows the past 7 days accurately, never resetting awkwardly at the start of a week.",
        "heatmap-feat-3": "<strong>Custom Purple Theme:</strong> Uses a beautiful color-coded square (■) gradient system.",
        "heatmap-feat-4": "<strong>Detailed Tooltips:</strong> Hover to see a date-wise contribution breakdown and total contributions over the tracked period.",
        "heatmap-colors-title": "🟪 Color Levels (Purple Theme)",
        "heatmap-colors-desc": "The heatmap utilizes the following color logic based on daily commit count:",
        "heatmap-table-col1": "Contributions",
        "heatmap-table-col2": "Color Hex",
        "heatmap-table-col3": "Meaning",
        "heatmap-meaning-0": "No contributions",
        "heatmap-meaning-1": "Low activity",
        "heatmap-meaning-2": "Moderate activity",
        "heatmap-meaning-3": "High activity",
        "heatmap-meaning-4": "Very high activity",
        "heatmap-install-title": "🛠️ Setup & Installation",
        "heatmap-install-step1": "1. Clone the Repository",
        "heatmap-install-step2": "2. GitHub Authentication",
        "heatmap-auth-desc1": "To make this module work, you need your GitHub username and a <b>Fine-Grained Personal Access Token (PAT)</b>.",
        "heatmap-auth-desc2": "Scope needed: <code>Repository access → All repositories</code>",
        "heatmap-auth-desc3": "Minimum required permissions for reading contribution data.",
        "heatmap-auth-link": "➡ <a href='https://github.com/settings/personal-access-tokens/new' target='_blank'>Generate your token here</a>.",
        "heatmap-install-step3": "3. Create <code>.env</code> File",
        "heatmap-env-desc": "Inside the cloned project directory, create a <code>.env</code> file with the following content:",
        "heatmap-waybar-title": "🖥️ Waybar Configuration",
        "heatmap-waybar-desc": "Add the following block to your Waybar <code>config.jsonc</code>. <i>(Make sure to update the path to where you placed the script and change the github URL to your own)</i>:",
        "heatmap-exec-warning": "<strong>⚠️ Execution Permission:</strong> Ensure the script is executable by running:<br><br><code>chmod +x ~/.config/waybar/scripts/weekly_commits</code>",
        "heatmap-css-title": "🎨 Styling (CSS)",
        "heatmap-css-desc": "Add the following styling to your Waybar <code>style.css</code>. It fits perfectly with dark/Catppuccin backgrounds:",
        "heatmap-btn-star": "⭐ Star on GitHub",
        "heatmap-footer-text": "© 2026 Ahmed x86 • Developed for the Linux Community ❄️",

        // === Waybar Hijri Calendar Page Translations (EN) ===
        "hijri-page-title": "Ahmed x86 - Waybar Hijri Calendar 🌙",
        "hijri-page-desc": "A stable, multi-language, offline-capable Hijri calendar for Linux status bars.",
        "hijri-about-title": "About",
        "hijri-about-desc": "This module provides an accurate Hijri calendar with <b>Multi-language support</b>. It intelligently solves Pango's RTL alignment bugs by utilizing localized headers and monospace formatting, ensuring a pixel-perfect grid in your tooltips.",
        "hijri-lang-title": "🌐 Supported Languages",
        "hijri-lang-desc": "Switch language using the <code>-lang</code> flag in your configuration:",
        "hijri-th-flag": "Flag",
        "hijri-th-lang": "Language",
        "hijri-th-headers": "Headers",
        "hijri-lang-ar": "Arabic (Default)",
        "hijri-lang-en": "English",
        "hijri-lang-fr": "French",
        "hijri-lang-de": "German",
        "hijri-lang-it": "Italian",
        "hijri-lang-es": "Spanish",
        "hijri-lang-tr": "Turkish",
        "hijri-lang-ku": "Kurdish",
        "hijri-lang-ja": "Japanese",
        "hijri-lang-ko": "Korean",
        "hijri-lang-id": "Indonesian",
        "hijri-feat-title": "✨ Key Features",
        "hijri-feat-1": "<strong>Multi-language Support:</strong> Choose between 11 languages including Arabic, English, French, German, Italian, Spanish, Turkish, Kurdish, Japanese, Korean, and Indonesian.",
        "hijri-feat-2": "<strong>Dynamic Month Length:</strong> Accurately handles 29/30 day months based on Hijri data.",
        "hijri-feat-3": "<strong>Offline Caching:</strong> Fetches data once per month for zero-lag performance.",
        "hijri-feat-4": "<strong>Authentic Islamic Events:</strong> Sunnah reminders like Ramadan, Eids, and White Days.",
        "hijri-feat-5": "<strong>Zero Dependencies:</strong> Pure Python script with minimal system footprint.",
        "hijri-install-title": "🛠️ Installation & Update",
        "hijri-install-desc": "Deploy the script directly using this command:",
        "hijri-update-warn": "<strong>⚠️ Crucial Update Step:</strong> If you are upgrading from an older version, you <b>must</b> clear the old cache file to apply the new format:<br><br><code>rm ~/.cache/waybar_hijri_cache.json</code>",
        "hijri-waybar-title": "🖥️ Waybar Configuration",
        "hijri-waybar-desc": "Add the following to your <code>config.jsonc</code> (change the lang flag to your preference):",
        "hijri-style-title": "🎨 Styling (Themes)",
        "hijri-style-desc": "Choose your favorite theme and add it to your Waybar <code>style.css</code>:",
        "hijri-theme-1": "1. Catppuccin (Mocha)",
        "hijri-theme-2": "2. Dracula",
        "hijri-theme-3": "3. Nord",
        "hijri-theme-4": "4. Gruvbox",
        "hijri-theme-5": "5. Tokyo Night",
        "hijri-perf-tip": "<strong>💡 Performance Tip:</strong> The script caches the entire month at <code>~/.cache/waybar_hijri_cache.json</code>. It only makes one API call per month!",
        "hijri-btn-repo": "View GitHub Repository",
        "hijri-footer-text": "© 2026 Ahmed x86 • Developed for the Linux Community ❄️",
        
        // === Wallpapers Page Translations (EN) ===
        "wall-page-title": "Ahmed x86 - Wallpapers Gallery 🖼️",
        "wall-page-desc": "A curated collection of minimalist and high-resolution wallpapers for Linux ricing and desktops.",
        "wall-col-title": "My Collection",
        "wall-col-desc": "Here are some of my favorite wallpapers used in my custom Arch Linux setups. Click on any image to view it in full resolution.",
        "wall-page-4-desc": "Page 4 - My curated collection of Reddit-sourced wallpapers for Linux ricing.",
        "wall-col-4-title": "My Collection (Part 4)",
        "wall-col-4-desc": "Here are some of the best Reddit-sourced wallpapers for my Arch Linux setup. Click on any image to view it in full resolution.",
        "wall-page-5-desc": "Page 5 - Royal wallpapers straight from my Hyprland dotfiles.",
        "wall-col-5-title": "My Collection (Part 5)",
        "wall-col-5-desc": "Here are the new royal wallpapers from my Hyprland dotfiles. Click on any image to view it in full resolution.",
        "wall-page-6-desc": "Page 6 - Cyberpunk, Neon Rain, and 4K Cars from my Arch Linux setup.",
        "wall-col-6-title": "My Collection (Part 6)",
        "wall-col-6-desc": "Here is the next batch of wallpapers from my Hyprland dotfiles. Click on any image to view it in full resolution.",
        "wall-page-7-desc": "Page 7 - The final part of my curated collection for Arch Linux setups.",
        "wall-col-7-title": "My Collection (Part 7)",
        "wall-col-7-desc": "Here are the final remaining wallpapers from my Arch Linux setup. Click on any image to view it in full resolution.",
    },
    ar: {
        "header-lang": "🌐 اللغة",
        "header-auth": "تسجيل الدخول / إنشاء حساب",
        "header-subtitle": "محب لنظام لينكس • طالب أمن سيبراني",
        "nav-about": "نبذة عني",
        "nav-projects": "المشاريع",
        "nav-wallpapers": "الخلفيات",
        "nav-github": "جيت هب",
        "nav-back-home": "← العودة للرئيسية",
        "nav-github-repo": "مستودع جيت هب",
        
        "about-title": "نبذة عني",
        "about-text": "أنا أحمد (معروف على الإنترنت باسم <strong>ahmed-x86</strong>)، أدرس نظم المعلومات والحاسبات. أتخصص في أنظمة لينكس (أستخدم Arch Linux كنظامي الأساسي) والأمن السيبراني. أستمتع بالبرمجة منخفضة المستوى بلغة التجميع (Assembly)، تحليل الشبكات، وبناء واجهات مخصصة باستخدام Hyprland و Waybar.",
        
        "projects-title": "مشاريعي",
        "proj-grub-title": "مُصلح GRUB 🛠️",
        "proj-grub-desc": "أداة استرداد شاملة وتلقائية لإصلاح GRUB على أنظمة UEFI بأمر واحد. جزء من حزمة إنقاذ نظام لينكس الخاصة بي.",
        "btn-view-repo": "عرض المستودع",
        
        "proj-asm-title": "بيئة تطوير Assembly",
        "proj-asm-desc": "إعداد برمجي لتشغيل وتصحيح أخطاء لغة التجميع بشكل أصلي على VS Code و VSCodium لأنظمة لينكس وويندوز.",
        
        "proj-hyprland-title": "ملفات إعداد Hyprland",
        "proj-hyprland-desc": "إعداداتي الشخصية لـ Hyprland. تركز على الإنتاجية، سير العمل، ومظهر نظيف وجذاب لنظام Arch Linux.",
        
        "proj-ghradar-title": "رادار GitHub لـ Waybar",
        "proj-ghradar-desc": "إضافة تفاعلية لـ Waybar تراقب نشاطك على GitHub في الوقت الفعلي مع شريط متحرك، تنبيهات صوتية، وإشعارات مرئية.",
        
        "proj-ghheatmap-title": "خريطة نشاط GitHub لـ Waybar",
        "proj-ghheatmap-desc": "أداة (Widget) باللون البنفسجي تجلب مساهماتك على جيت هب لآخر 7 أيام باستخدام GraphQL API.",
        
        "proj-hijri-title": "تقويم هجري لـ Waybar",
        "proj-hijri-desc": "سكربت بايثون مستقر لتقويم هجري ديناميكي في Waybar، يدعم الاتجاه من اليمين لليسار (RTL) وبدون أي حزم إضافية.",
        
        "proj-charge-title": "مؤشر شحن الهاتف لـ Waybar",
        "proj-charge-desc": "سكربت Bash خفيف لعرض حالة بطارية هاتف أندرويد في Waybar عبر ربطه بـ KDE Connect.",
        
        "proj-scripts-title": "سكربتات الأتمتة",
        "proj-scripts-desc": "مجموعة من سكربتات Bash لأتمتة المهام اليومية وتحسين سير العمل على واجهة سطح مكتب Arch Linux.",
        
        "media-section-title": "الصور والفيديو",
        "proj-wallpapers-title": "معرض الخلفيات",
        "proj-wallpapers-desc": "مجموعة منتقاة من خلفيات 4K البسيطة والجمالية المناسبة تمامًا لتخصيص لينكس وإعدادات Arch Linux و Hyprland.",
        "btn-browse-wallpapers": "تصفح الخلفيات",
        
        "proj-gatherings-title": "تجمعات لينكس",
        "proj-gatherings-desc": "استكشف التجمعات، النقاشات، والأحداث المتعلقة بنظام لينكس، البرمجيات مفتوحة المصدر، والأمن السيبراني.",
        "btn-view-gatherings": "عرض تجمعات لينكس",
        
        "footer-text": "© 2026 أحمد x86 • تم البناء على Arch Linux ❄️",
        
        "btn-feedback": "ملاحظاتك",
        "feedback-title": "أرسل لنا ملاحظاتك",
        "feedback-subtitle": "نحن نهتم برأيك (نوعاً ما).",
        "feedback-name-placeholder": "اسمك",
        "feedback-email-placeholder": "بريدك الإلكتروني",
        "feedback-desc-placeholder": "اشرح مشكلتك هنا...",
        "feedback-submit": "إرسال الملاحظات",
        
        "lang-modal-title": "اختر اللغة",
        "lang-modal-subtitle": "اختر لغة الموقع",
        "btn-copy": "نسخ",

        // === ASM Page Translations (AR) ===
        "asm-page-title": "أحمد x86 - بيئة تطوير لغة التجميع (Assembly) 🚀",
        "asm-page-desc": "مستودع شامل صُمم لبدء رحلتك في تطوير لغة التجميع (ASM) بكل سلاسة.",
        "asm-intro-text": "توفر هذه البيئة دعماً جاهزاً للعمل لأنظمة Linux x64 و Windows (x86/x64)، وتتميز بإعدادات VS Code مجهزة مسبقاً لسير عمل سلس.",
        "asm-quick-install": "🛠️ التثبيت السريع",
        "asm-choose-weapon": "اختر سلاحك (نظام التشغيل) وقم بتشغيل الأمر المقابل لتهيئة بيئتك فوراً:",
        "asm-linux-install": "🐧 لينكس (تثبيت بأمر واحد)",
        "asm-linux-desc": "يدعم Arch، Debian/Ubuntu، Fedora، Alpine، openSUSE، Solus، Gentoo، Puppy Linux، و Void.",
        "asm-win10-install": "🪟 ويندوز 10 / 11 (تثبيت عبر PowerShell)",
        "asm-win10-desc": "مُحسّن لبيئات ويندوز الحديثة.",
        "asm-win7-install": "🏛️ ويندوز 7 (دعم الأنظمة القديمة)",
        "asm-win7-desc": "سكربت مخصص لدعم التوافق مع ويندوز 7.",
        "asm-key-features": "✨ الميزات الأساسية",
        "asm-feat-1": "<strong>دعم مزدوج للمنصات:</strong> مثبتات أصلية لكل من ويندوز ولينكس، لضمان استقرار بيئة التطوير الخاصة بك في أي مكان.",
        "asm-feat-2": "<strong>تكامل مع VS Code:</strong> ملفات <code>tasks.json</code> و <code>launch.json</code> مجهزة مسبقاً لتسمح لك ببناء وتصحيح الكود باختصار واحد (<code>Ctrl+Shift+B</code>).",
        "asm-feat-3": "<strong>أداة CLI عالمية:</strong> يتم تثبيت أمر <code>asm-run</code> المخصص على النظام، مما يتيح لك تجميع واختبار ملفات <code>.asm</code> مباشرة من أي تيرمينال بدون فتح المحرر.",
        "asm-feat-4": "<strong>إدارة ذكية للاعتماديات:</strong> يكتشف تلقائياً مدير الحزم الخاص بك على لينكس ويتخطى التنزيلات المكررة، بينما يقوم بإعداد NASM على ويندوز تلقائياً.",
        "asm-feat-5": "<strong>دعم الأنظمة القديمة:</strong> مثبت خاص لـ <strong>ويندوز 7</strong> لضمان عدم تقييد تطوير الأسمبلي بإصدار نظام التشغيل.",
        "asm-feat-6": "<strong>تصريف متقاطع (Cross-Compilation):</strong> أدوات جاهزة للاستخدام لتجميع واختبار ثنائيات ويندوز مباشرة من لينكس باستخدام Wine و MinGW.",
        "asm-smart-engine": "🧠 ميزات المحرك الذكي",
        "asm-smart-1": "<strong>تنفيذ مضاد للأخطاء:</strong> يحتوي على فحوصات مدمجة لاستقرار الشبكة، حلقات صارمة للتحقق من الإدخال، واصطياد لـ <code>Ctrl+C</code> ينظف التنزيلات الجزئية تلقائياً عند المقاطعة.",
        "asm-smart-2": "<strong>الأمان أولاً:</strong> يطبق فحوصات سلامة <strong>SHA256</strong> صارمة للملفات الخارجية لضمان أصالتها ومنع اختراقها.",
        "asm-smart-3": "<strong>متوافق مع عدة محررات:</strong> يفحص ويكتشف بيئة التطوير الخاصة بك تلقائياً (VS Code, VSCodium, Cursor) ويهيئ إضافات الأسمبلي.",
        "asm-smart-4": "<strong>تتبع شامل للحزم:</strong> يكتشف ما إذا كان محررك مثبتاً عبر مدير الحزم الأصلي أو Snap أو Flatpak ويهيئ الإضافات بالصلاحيات الصحيحة.",
        "asm-smart-5": "<strong>تصحيح تلقائي للمسارات:</strong> يُحدث مسارات <code>launch.json</code> و <code>tasks.json</code> ديناميكياً بناءً على اسم المستخدم الخاص بك ومسار المجلد.",
        "asm-final-note-title": "🎭 ملاحظة ختامية",
        "asm-important-note": "<strong>[!هام]</strong><br>تم بناء هذا المشروع لإثبات أن \"فهم لينكس\" ليس مجرد كلام، بل هو بناء حلول تعمل على <strong>أكثر من 9 توزيعات</strong> بنقرة واحدة.",
        "asm-stay-hard": "استمر بقوة، وواصل البرمجة. 🚀",
        "asm-arch-note": "<strong>ملاحظة لمستخدمي Arch:</strong> لأن مقولة \"I use Arch btw\" لا ينبغي أن تعني قضاء ثلاث ساعات في الإعداد. لقد قمنا بتغطية الأمر من أجلك. 😎",

        // === gh-radar Page Translations (AR) ===
        "ghradar-page-title": "أحمد x86 - رادار GitHub لـ Waybar 📡",
        "ghradar-page-desc": "إضافة ديناميكية وتفاعلية لـ Waybar تراقب نشاطك على جيت هب في الوقت الفعلي.",
        "ghradar-demo-caption": "شاهد الشريط المتحرك والتنبيهات الخاصة بـ gh-radar أثناء العمل!",
        "ghradar-features-title": "✨ الميزات الأساسية",
        "ghradar-feat-1": "<strong>شريط متحرك (Ticker):</strong> يتغير نص Waybar ديناميكياً عند حدوث دفع (Push) جديد. يظهر الفرع ورسالة الـ Commit، ثم اسم المستودع، وأخيراً يعود لاسم المستخدم الخاص بك.",
        "ghradar-feat-2": "<strong>تنبيهات صوتية:</strong> يشغل صوت إشعار بنمط ريترو فوراً عند اكتشاف نشاط جديد.",
        "ghradar-feat-3": "<strong>إشعارات بالصور الشخصية:</strong> يرسل إشعاراً لسطح المكتب يحتوي على الصورة الشخصية الحقيقية (Avatar) للمستخدم على جيت هب مع تفاصيل الـ Commit.",
        "ghradar-feat-4": "<strong>أزرار تفاعلية:</strong> كليك يسار لفتح ملفك الشخصي على جيت هب، وكليك يمين لفتح الإشعارات مباشرة من Waybar.",
        "ghradar-feat-5": "<strong>تحديث يدوي (جديد!):</strong> اضغط بالزر الأوسط للماوس على الإضافة لجلب أحدث التحديثات فوراً باستخدام إشارات لينكس (<code>SIGUSR1</code>).",
        "ghradar-feat-6": "<strong>إدارة ذكية للموارد:</strong> فترات استعلام ديناميكية (كل 10 ثوانٍ عند النشاط، و 60 ثانية في الخمول) أو وضع السبات الكامل (<code>-t 0</code>) لتوفير البطارية والإنترنت.",
        "ghradar-feat-7": "<strong>أيقونات مخصصة (جديد!):</strong> اختر من بين 10 أيقونات مختلفة من Nerd Fonts (مثل Octocat أو شعار Git) باستخدام المُعامل <code>-icon</code>.",
        "ghradar-feat-8": "<strong>مُحسّن للـ API:</strong> يستخدم ترويسات <code>ETag</code> الخاصة بجيت هب لاحترام حدود معدل طلبات الـ API.",
        "ghradar-install-title": "🛠️ التثبيت والإعداد",
        "ghradar-install-step1": "1. الاستنساخ ونسخ الملفات",
        "ghradar-install-step2": "2. إضافة بيانات الاعتماد (.env)",
        "ghradar-env-desc1": "أنشئ ملف <code>.env</code> للمصادقة مع جيت هب:",
        "ghradar-env-desc2": "أضف التالي (واستبدله ببياناتك):",
        "ghradar-install-step3": "3. تثبيت الاعتماديات",
        "ghradar-dep-desc": "بناءً على توزيعة لينكس الخاصة بك، قم بتثبيت مكتبات بايثون المطلوبة. ستحتاج أيضاً إلى مشغل صوت (<code>mpv</code> أو <code>paplay</code>) وخادم إشعارات (<code>libnotify</code>).",
        "ghradar-dep-arch": "لـ Arch Linux / Manjaro:",
        "ghradar-dep-ubuntu": "لـ Ubuntu / Debian (أو باستخدام pip):",
        "ghradar-usage-title": "⚙️ الاستخدام والمُعاملات",
        "ghradar-usage-desc": "يدعم السكربت تمرير مُعاملات (Arguments) لتخصيص سلوكه:",
        "ghradar-usage-arg1": "<code>my_repos_only</code>: يُفعل التنبيهات فقط للمستودعات التي تمتلكها (يتجاهل النشاط من المستودعات الأخرى التي تتابعها).",
        "ghradar-usage-arg2": "<code>-t 0</code>: <strong>الوضع اليدوي</strong>. لن يستعلم السكربت من جيت هب تلقائياً، بل سيدخل في وضع السبات حتى تضغط بالزر الأوسط للماوس على إضافة Waybar.",
        "ghradar-usage-arg3": "<code>-icon &lt;1-10&gt;</code>: <strong>(جديد!)</strong> يحدد الأيقونة المعروضة في Waybar. اختر رقماً من 1 إلى 10 (مثال: <code>-icon 2</code> لعرض أيقونة Octocat).",
        "ghradar-waybar-title": "🖥️ إعدادات Waybar",
        "ghradar-waybar-step1": "1. إعداد الإضافة (<code>config.jsonc</code>)",
        "ghradar-pro-tip": "💡 نصيحة للمحترفين:",
        "ghradar-pro-tip-desc": "أضف <code>\"reload_style_on_change\": true,</code> في أعلى ملف إعداد Waybar الخاص بك. هذا يسمح لـ Waybar بتطبيق التغييرات فوراً عند تعديل ملف الإعداد أو الستايل بدون الحاجة لإعادة تشغيل يدوية!",
        "ghradar-waybar-desc1": "أضف هذه الوحدة إلى ملف إعداد Waybar الخاص بك (تحت <code>modules-left</code>، <code>modules-center</code>، أو <code>modules-right</code>):",
        "ghradar-waybar-desc2": "<em>(ملاحظة: قم بتغيير <code>ahmed-x86</code> إلى اسم المستخدم الفعلي الخاص بك على جيت هب في رابط الـ <code>on-click</code>).</em>",
        "ghradar-waybar-step2": "2. المظهر (<code>style.css</code>)",
        "ghradar-style-desc": "اختر الثيم الذي يتناسب مع إعداد Waybar الحالي الخاص بك وأضفه إلى ملف <code>style.css</code>.",
        "ghradar-style-1": "1. الافتراضي (GitHub Dark)",
        "ghradar-style-2": "2. Catppuccin (Mocha)",
        "ghradar-style-3": "3. Dracula",
        "ghradar-restart-note": "<strong>إعادة تشغيل Waybar:</strong> قم بتطبيق التغييرات عن طريق إعادة تشغيل Waybar باستخدام <code>killall waybar && waybar & disown</code> (فقط إذا لم تقم بتفعيل <code>reload_style_on_change</code>).",
        "ghradar-btn-repo": "عرض المستودع على GitHub",

        // === GRUB Fixer Page Translations (AR) ===
        "grub-page-title": "أحمد x86 - مُصلح GRUB 🛠️",
        "grub-page-desc": "حزمة استرداد شاملة وتلقائية لإصلاح محمل الإقلاع (GRUB) لأنظمة UEFI و Legacy BIOS، تدعم التشغيل الآلي بدون تدخل بشري، المسح العميق الذكي، واكتشاف بيئة النواة.",
        "grub-about-title": "عن المشروع",
        "grub-about-desc": "أداة <b>GRUB Fixer (إصدار V18 - تحديث الأتمتة الكاملة)</b> تأخذ عملية إنقاذ النظام إلى أقصى حد. هو سكربت Bash مضاد للأخطاء مصمم لإصلاح محمل الإقلاع GRUB على أنظمة <b>UEFI و Legacy BIOS</b>. يقدم الإصدار <b>V18 مُعاملات سطر الأوامر (CLI Flags) لعمليات التشغيل الآلية بالكامل</b>، مبنياً على <b>محرك المسح العميق</b> و<b>اكتشاف بيئة الكيرنل</b> الذي تم تقديمه في V17 لإزالة أي حيرة للمستخدم أثناء إنقاذ النظام.",
        "grub-v18-note": "<strong>🚀 جديد في V18:</strong> يدعم السكربت الآن <b>الأتمتة الكاملة عبر سطر الأوامر</b>! قم بتمرير <code>-env l -auto</code> لتجاوز جميع رسائل التأكيد والسماح للسكربت بإصلاح GRUB في صمت خلال ثوانٍ بناءً على الكشف التلقائي.",
        "grub-flags-title": "🚩 دليل مُعاملات V18 (CLI Flags)",
        "grub-flags-desc": "يقدم الإصدار V18 معاملات لتخطي الأسئلة وتمكين التشغيل الآلي (Headless):",
        "grub-flag-1": "<strong><code>-env l</code> أو <code>-env live</code>:</strong> إجبار السكربت على افتراض العمل من <b>بيئة حية</b> (USB/ISO).",
        "grub-flag-2": "<strong><code>-env h</code> أو <code>-env host</code>:</strong> إجبار السكربت على افتراض العمل من <b>نظام حقيقي مُثبت</b>.",
        "grub-flag-3": "<strong><code>-auto</code>:</strong> معامل \"الوضع الفائق\". يتخطى جميع مطالبات التأكيد <code>(y/n)</code>، ويفترض نقاط التثبيت الافتراضية، وينفذ الإصلاح فوراً.",
        "grub-flag-4": "<strong><code>--version</code> أو <code>-v</code>:</strong> طباعة الإصدار الحالي والخروج.",
        "grub-intel-title": "✨ تحديث الذكاء (V17 و V18)",
        "grub-intel-1": "<strong>أتمتة بدون واجهة (V18):</strong> تمرير المعاملات مباشرة عبر خط الأوامر لتنفيذ إصلاحات معقدة بدون ضغطة زر واحدة.",
        "grub-intel-2": "<strong>كشف أوامر الكيرنل (V17):</strong> يحلل <code>/proc/cmdline</code> للتمييز الفوري بين أسطوانات الـ Live ISO (مثل Archiso و Casper) والأنظمة المثبتة فعلياً.",
        "grub-intel-3": "<strong>محرك المسح العميق (V17):</strong> يقوم بعمل مسح وربط (Mount) مخفي للأقسام في وضع القراءة فقط للعثور على ملف <code>fstab</code> وحل معرّفات الـ UUIDs و PARTUUIDs قبل أي تدخل من المستخدم.",
        "grub-intel-4": "<strong>تنبيه موحد بنقرة واحدة (V17):</strong> يدمج بين كشف البيئة وتأكيد تخطيط الأقراص في شاشة ملخص واحدة نظيفة.",
        "grub-evo-title": "⚙️ تاريخ التطور (V16 - V12)",
        "grub-evo-1": "<strong>اكتشاف الوضع المحلي (V16):</strong> يكتشف بذكاء ما إذا تم تشغيله من نظام التشغيل المُثبت، ويتخطى بيئة الـ chroot لإصلاح GRUB محلياً في ثوانٍ.",
        "grub-evo-2": "<strong>كشف معماريات UEFI الديناميكي (V15):</strong> يكتشف معماريات UEFI النادرة (32-bit) ويحول هدف GRUB تلقائياً إلى <code>i386-efi</code>.",
        "grub-evo-3": "<strong>مؤقت التنفيذ الديناميكي (V14):</strong> يوفر رسائل تفاعلية بأسلوب الـ Gamers بناءً على سرعة إتمام الإصلاح.",
        "grub-evo-4": "<strong>دعم OS Prober (V13):</strong> تفعيل <code>GRUB_DISABLE_OS_PROBER=false</code> تلقائياً لضمان اكتشاف الويندوز أو أي توزيعات أخرى.",
        "grub-evo-5": "<strong>دعم Legacy BIOS واستخراج القرص الذكي (V12):</strong> دعم كامل لـ <code>i386-pc</code> مع استخراج ذكي للقرص الأب.",
        "grub-core-title": "🧠 ميزات الـ Power User الأساسية",
        "grub-core-1": "<strong>تحليل FSTAB بدون تدخل:</strong> يحل علامات الـ <code>UUID</code> و <code>PARTUUID</code> فوراً، ويحدد مسارات مجلدات Btrfs الفرعية بدون إدخال يدوي.",
        "grub-core-2": "<strong>نظام بدائل ثلاثي (3-Tier):</strong> ينتقل بسلاسة من الوضع الاحترافي (FSTAB) إلى المسح الذكي التلقائي، ثم كحل أخير للإدخال اليدوي.",
        "grub-core-3": "<strong>حلقة Btrfs مضادة للأخطاء:</strong> التحقق التفاعلي من الهياكل الفرعية المعقدة (مثل <code>@</code>، <code>@home</code>، <code>@log</code>).",
        "grub-core-4": "<strong>إنقاذ الأجهزة الوهمية والـ NVRAM:</strong> فرض استخدام مُعامل <code>--removable</code> لبرامج الـ UEFI العنيدة وبيئات QEMU/KVM.",
        "grub-usage-title": "🛠️ الاستخدام",
        "grub-usage-desc": "قم بتشغيل \"سلاح الإنقاذ الشامل\" مباشرة من التيرمينال الخاص بك:",
        "grub-usage-opt1-title": "الخيار الأول: أمر واحد سريع (الوضع التفاعلي)",
        "grub-usage-opt1-desc": "التجربة التفاعلية الكلاسيكية، الذكية، والموحدة:",
        "grub-usage-opt2-title": "الخيار الثاني: آلي بالكامل (وضع عدم التدخل) 💥",
        "grub-usage-opt2-desc": "تخطى كل الأسئلة ودع السكربت يصلح الـ GRUB في صمت بناءً على الكشف التلقائي (مثالي للاستخدام من فلاشة Live USB):",
        "grub-usage-opt3-title": "الخيار الثالث: التحميل اليدوي",
        "grub-version-title": "📜 سجل الإصدارات",
        "grub-version-summary": "انقر لعرض سجل الإصدارات بالكامل",
        "grub-th-version": "الإصدار",
        "grub-th-changes": "التغييرات الرئيسية",
        "grub-v1": "المنطق الأولي اليدوي لـ chroot.",
        "grub-v2": "التحقق من الإدخال وفحص الأجهزة.",
        "grub-v3": "تنظيف مجلد <code>/mnt</code> تلقائياً باستخدام (umount -R).",
        "grub-v4": "وضع الأمان (Failsafe)، اكتشاف نظام التشغيل، وأتمتة الـ EOF.",
        "grub-v5": "دعم إنقاذ الأجهزة الوهمية / NVRAM ودعم خط أنابيب TTY.",
        "grub-v6": "المسح التلقائي الذكي وسير عمل مقترح للمستخدم.",
        "grub-v7": "دعم التخزين المخصص الديناميكي (تحديث الإنقاذ).",
        "grub-v8": "التحقق الذكي من الـ EFI، تسجيل الأحداث، وصلاحيات الروت (تحديث الأمان).",
        "grub-v9": "دعم مجلدات Btrfs الفرعية مع التوجيه الذكي.",
        "grub-v10": "منطق ربط EFI الديناميكي، حلقة تحقق إجبارية، وتحسين الكشف التلقائي.",
        "grub-v11": "وضع الانطلاق بدون تدخل (محلل fstab)، نظام بدائل ثلاثي المراحل.",
        "grub-v12": "إضافة دعم Legacy BIOS (i386-pc)، المسح التلقائي، واستخراج القرص المستهدف.",
        "grub-v13": "إضافة دعم OS Prober لاكتشاف أنظمة التشغيل المزدوجة تلقائياً (مثل ويندوز).",
        "grub-v14": "إضافة مؤقت التنفيذ الديناميكي مع ردود فعل بشرية بأسلوب الـ Gamers (تحديث السرعة).",
        "grub-v15": "إضافة الدعم الشامل لـ UEFI (32-bit/i386-efi) مع كشف المعمارية الديناميكي.",
        "grub-v16": "إضافة وضع In-Situ (المحلي) لإصلاح GRUB مباشرة من النظام المشغل بدون Live USB أو chroot.",
        "grub-v17": "محرك المسح العميق، اكتشاف معلمات الكيرنل، ومطالبة موحدة لتجربة المستخدم.",
        "grub-v18": "<b>الحالي:</b> إضافة مُعاملات سطر الأوامر (--version, -env l/h, -auto) لأتمتة كاملة بدون أي تفاعل.",
        "grub-req-title": "📋 متطلبات النظام",
        "grub-req-1": "<strong>البيئة:</strong> فلاشة لينكس حية (Arch، CachyOS، إلخ) أو نظام مثبت محلياً.",
        "grub-req-2": "<strong>المعمارية:</strong> UEFI (x86_64/i386) أو Legacy BIOS (i386-pc).",
        "grub-req-3": "<strong>الصلاحيات:</strong> يتطلب وصول Sudo/Root.",
        "grub-warn-title": "⚠️ إخلاء مسؤولية",
        "grub-warn-desc": "قم دائماً بالتحقق من ملخص <b>المسح العميق</b> قبل تأكيد عملية الإصلاح، خاصة في الأنظمة متعددة التشغيل (Dual-boot).",
        "grub-warn-v19": "<strong>⚠️ مخطط لـ V19:</strong> إجراء أبحاث لإضافة دعم أتمتة تشفير <b>LUKS</b> لإصلاح الأقسام المشفرة بسلاسة.",
        "grub-btn-star": "⭐ ضع نجمة على GitHub",
        "grub-footer-text": "© 2026 أحمد x86 • جزء من حزمة إنقاذ أنظمة لينكس ❄️",

        // === Hyprland Dotfiles Page Translations (AR) ===
        "hypr-page-title": "🍙 أحمد x86 - ملفات إعداد Hyprland",
        "hypr-page-desc": "بيئة عمل مبسطة، مخصصة بعناية، وعملية بالكامل لواجهة Hyprland على نظام Arch Linux.",
        "hypr-about-title": "نبذة",
        "hypr-about-desc1": "مرحباً بك في إعدادات <b>Hyprland</b> الشخصية الخاصة بي. مُصممة لتجمع بين الجمالية والأداء باستخدام لوحة ألوان Catppuccin.",
        "hypr-about-desc2": "<b>تجربة النظام البيئي المتكامل:</b> تتميز بإعداد تلقائي تفاعلي وسلس لربط حسابك على جيت هب (مؤشر المساهمات والرادار) وهاتفك المحمول (عبر KDE Connect).",
        "hypr-software-title": "البرامج والأدوات",
        "hypr-waybar-title": "إضافات Waybar",
        "hypr-mod-left": "الإضافات اليسرى",
        "hypr-mod-l1": "قائمة الطاقة (wlogout)",
        "hypr-mod-l2": "نشاط GitHub",
        "hypr-mod-l3": "رادار GitHub",
        "hypr-mod-l4": "مُبدّل مساحات العمل",
        "hypr-mod-l5": "مانع السكون (Idle Inhibitor)",
        "hypr-mod-l6": "تحديثات النظام",
        "hypr-mod-center": "الإضافات الوسطى",
        "hypr-mod-c1": "أداة التقاط الألوان",
        "hypr-mod-c2": "التقويم الهجري",
        "hypr-mod-c3": "الساعة",
        "hypr-mod-c4": "نقاط الخصوصية (Privacy Dots)",
        "hypr-mod-c5": "أيقونات النظام (System Tray)",
        "hypr-mod-right": "الإضافات اليمنى",
        "hypr-mod-r1": "التحكم بالوسائط",
        "hypr-mod-r2": "تخطيط لوحة المفاتيح",
        "hypr-mod-r3": "البلوتوث والشبكة",
        "hypr-mod-r4": "البطارية وملفات الطاقة",
        "hypr-mod-r5": "الصوت والميكروفون",
        "hypr-mod-r6": "تبديل الإشعارات",
        "hypr-install-title": "التثبيت",
        "hypr-install-online": "التثبيت المباشر (الأسرع والمؤتمت بالكامل)",
        "hypr-install-offline": "التثبيت اليدوي (Offline)",
        "hypr-gallery-title": "معرض الصور",
        "hypr-btn-repo": "عرض المستودع على GitHub",

        // === Arch Sessions Page Translations (AR) ===
        "arch-page-title": "أحمد x86 - جلسات لينكس المسجلة 🖥️",
        "arch-page-desc": "استكشف مملكة لينكس من خلال جلسات مسجلة تعلمك كل شيء بدءاً من التثبيت وحتى احتراف سطر الأوامر (Terminal).",
        "arch-sessions-title": "الجلسات المسجلة",
        "arch-sessions-desc": "جلسات بسيطة وعملية ترشدك نحو إتقان نظام لينكس. اضغط على أي صورة مصغرة لبدء المشاهدة.",
        "arch-zorin-title": "دليل تثبيت Zorin OS",
        "arch-zorin-desc": "شرح شامل وخطوة بخطوة لكيفية تثبيت نظام Zorin OS من الصفر. مثالي لتجربة لينكس سلسة وجذابة بصرياً.",
        "arch-cmds-title": "أوامر لينكس الأساسية: الدليل المتقدم",
        "arch-cmds-desc": "ارتقِ بمهاراتك في التيرمينال إلى المستوى التالي. تقدم هذه الجلسة شرحاً متعمقاً ومتقدماً لأهم أوامر لينكس الأساسية وكيفية احترافها.",
        "pagination-prev": "« السابق",
        "pagination-next": "التالي »",

        // === Mobile Charge Indicator Page Translations (AR) ===
        "mob-page-title": "أحمد x86 - مؤشر شحن الهاتف لـ Waybar 📱",
        "mob-page-desc": "سكربت Bash خفيف يعرض بطارية هاتفك في Waybar باستخدام KDE Connect.",
        "mob-about-title": "نبذة",
        "mob-about-desc": "سكربت أنيق وخفيف الوزن يعرض حالة بطارية هاتفك المحمول مباشرة في <b>Waybar</b> باستخدام <b>KDE Connect</b>. مثالي لمستخدمي Hyprland و Sway.",
        "mob-features-title": "الميزات",
        "mob-feat-1": "اكتشاف تلقائي لمعرّف الهاتف المتصل",
        "mob-feat-2": "ألوان بطارية ديناميكية (طبيعي / تحذير / حرج)",
        "mob-feat-3": "أيقونة مؤشر الشحن",
        "mob-feat-4": "انقر على الإضافة لعمل Ping لهاتفك",
        "mob-install-title": "التثبيت",
        "mob-install-desc1": "قم بتشغيل الأوامر التالية في التيرمينال لتثبيت السكربت:",
        "mob-install-desc2": "سيقوم السكربت تلقائياً بنسخ <b>mobile.sh</b> إلى:",
        "mob-waybar-conf-title": "إعدادات Waybar",
        "mob-waybar-style-title": "تنسيق Waybar",
        "mob-btn-repo": "عرض المستودع على GitHub",

        // === GitHub Heatmap Page Translations (AR) ===
        "heatmap-page-title": "أحمد x86 - خريطة نشاط GitHub لـ Waybar 🟪",
        "heatmap-page-desc": "إضافة ديناميكية باللون البنفسجي لـ Waybar. تجلب مساهماتك لآخر 7 أيام باستخدام GraphQL API.",
        "heatmap-about-title": "نبذة",
        "heatmap-about-desc": "سكربت مدمج للتيرمينال أو شريط الحالة يجلب <b>نشاط مساهماتك على GitHub لآخر 7 أيام متتالية</b> باستخدام GraphQL API ويعرض خريطة حرارية (Heatmap) مخصصة باللون البنفسجي (■) مع تلميحات مفصلة. مصمم للتكامل السلس مع أشرطة الحالة مثل <b>Waybar</b>، <b>Polybar</b>، أو أي إضافة سطح مكتب مخصصة.",
        "heatmap-note": "<strong>💡 ملاحظة:</strong> هذا السكربت هو نسخة معدلة (Fork) من <a href='https://github.com/ad1822/weekly-github-waybar-module' target='_blank'>إضافة ad1822</a>. تمت إعادة كتابته ليعرض <b>نافذة 7 أيام متتالية</b> (لتجنب ظهور مربعات فارغة في بداية الأسبوع) ويتميز <b>بنظام ألوان بنفسجي</b> مخصص.",
        "heatmap-features-title": "✨ الميزات الأساسية",
        "heatmap-feat-1": "<strong>بيانات في الوقت الفعلي:</strong> يجلب بيانات المساهمات مباشرة من GraphQL API الخاصة بجيت هب.",
        "heatmap-feat-2": "<strong>نافذة 7 أيام متتالية:</strong> يعرض دائماً الأيام الـ 7 الماضية بدقة، ولا يُعاد تعيينه بشكل مزعج في بداية الأسبوع.",
        "heatmap-feat-3": "<strong>ثيم بنفسجي مخصص:</strong> يستخدم نظام تدرج لوني جميل ومميز بالمربعات (■).",
        "heatmap-feat-4": "<strong>تلميحات مفصلة:</strong> مرر الماوس لرؤية تفاصيل المساهمات لكل يوم وإجمالي المساهمات خلال الفترة المتعقبة.",
        "heatmap-colors-title": "🟪 مستويات الألوان (الثيم البنفسجي)",
        "heatmap-colors-desc": "تستخدم الخريطة الحرارية منطق الألوان التالي بناءً على عدد الـ Commits اليومية:",
        "heatmap-table-col1": "المساهمات",
        "heatmap-table-col2": "كود اللون (Hex)",
        "heatmap-table-col3": "المعنى",
        "heatmap-meaning-0": "لا توجد مساهمات",
        "heatmap-meaning-1": "نشاط منخفض",
        "heatmap-meaning-2": "نشاط متوسط",
        "heatmap-meaning-3": "نشاط عالٍ",
        "heatmap-meaning-4": "نشاط عالٍ جداً",
        "heatmap-install-title": "🛠️ الإعداد والتثبيت",
        "heatmap-install-step1": "1. استنساخ المستودع",
        "heatmap-install-step2": "2. المصادقة مع GitHub",
        "heatmap-auth-desc1": "لكي تعمل هذه الإضافة، تحتاج إلى اسم المستخدم الخاص بك على جيت هب و <b>رمز وصول شخصي دقيق الصلاحيات (PAT)</b>.",
        "heatmap-auth-desc2": "الصلاحيات المطلوبة: <code>Repository access → All repositories</code>",
        "heatmap-auth-desc3": "الحد الأدنى من الأذونات المطلوبة لقراءة بيانات المساهمات.",
        "heatmap-auth-link": "➡ <a href='https://github.com/settings/personal-access-tokens/new' target='_blank'>قم بإنشاء الرمز الخاص بك من هنا</a>.",
        "heatmap-install-step3": "3. إنشاء ملف <code>.env</code>",
        "heatmap-env-desc": "داخل مجلد المشروع المستنسخ، قم بإنشاء ملف <code>.env</code> بالمحتوى التالي:",
        "heatmap-waybar-title": "🖥️ إعدادات Waybar",
        "heatmap-waybar-desc": "أضف الكتلة التالية إلى ملف <code>config.jsonc</code> الخاص بـ Waybar. <i>(تأكد من تحديث المسار إلى مكان وضع السكربت وتغيير رابط جيت هب إلى الرابط الخاص بك)</i>:",
        "heatmap-exec-warning": "<strong>⚠️ أذونات التشغيل:</strong> تأكد من أن السكربت قابل للتشغيل عن طريق تنفيذ:<br><br><code>chmod +x ~/.config/waybar/scripts/weekly_commits</code>",
        "heatmap-css-title": "🎨 المظهر (CSS)",
        "heatmap-css-desc": "أضف التنسيق التالي إلى ملف <code>style.css</code> الخاص بـ Waybar. إنه يتناسب تماماً مع الخلفيات الداكنة أو ثيم Catppuccin:",
        "heatmap-btn-star": "⭐ ضع نجمة على GitHub",
        "heatmap-footer-text": "© 2026 أحمد x86 • تم التطوير لمجتمع لينكس ❄️",

        // === Waybar Hijri Calendar Page Translations (AR) ===
        "hijri-page-title": "أحمد x86 - التقويم الهجري لـ Waybar 🌙",
        "hijri-page-desc": "تقويم هجري مستقر، متعدد اللغات، ويعمل بدون إنترنت لأشرطة الحالة في لينكس.",
        "hijri-about-title": "نبذة",
        "hijri-about-desc": "توفر هذه الإضافة تقويماً هجرياً دقيقاً مع <b>دعم متعدد اللغات</b>. تحل بذكاء مشاكل محاذاة Pango من اليمين لليسار (RTL) باستخدام رؤوس مترجمة وتنسيق Monospace، مما يضمن شبكة مثالية في التلميحات (Tooltips).",
        "hijri-lang-title": "🌐 اللغات المدعومة",
        "hijri-lang-desc": "غيّر اللغة باستخدام معامل <code>-lang</code> في ملف الإعداد:",
        "hijri-th-flag": "المعامل (Flag)",
        "hijri-th-lang": "اللغة",
        "hijri-th-headers": "رؤوس الأيام",
        "hijri-lang-ar": "العربية (الافتراضي)",
        "hijri-lang-en": "الإنجليزية",
        "hijri-lang-fr": "الفرنسية",
        "hijri-lang-de": "الألمانية",
        "hijri-lang-it": "الإيطالية",
        "hijri-lang-es": "الإسبانية",
        "hijri-lang-tr": "التركية",
        "hijri-lang-ku": "الكردية",
        "hijri-lang-ja": "اليابانية",
        "hijri-lang-ko": "الكورية",
        "hijri-lang-id": "الإندونيسية",
        "hijri-feat-title": "✨ الميزات الأساسية",
        "hijri-feat-1": "<strong>دعم متعدد اللغات:</strong> اختر من بين 11 لغة بما في ذلك العربية، الإنجليزية، الفرنسية، الألمانية، الإيطالية، الإسبانية، التركية، الكردية، اليابانية، الكورية، والإندونيسية.",
        "hijri-feat-2": "<strong>طول شهر ديناميكي:</strong> يتعامل بدقة مع الأشهر ذات 29 أو 30 يوماً بناءً على البيانات الهجرية.",
        "hijri-feat-3": "<strong>تخزين مؤقت (Offline Cache):</strong> يجلب البيانات مرة واحدة شهرياً لأداء سريع بدون تأخير.",
        "hijri-feat-4": "<strong>أحداث إسلامية موثوقة:</strong> تذكيرات السنن مثل رمضان، الأعياد، والأيام البيض.",
        "hijri-feat-5": "<strong>بدون اعتماديات:</strong> سكربت بايثون نقي بحد أدنى من استهلاك النظام.",
        "hijri-install-title": "🛠️ التثبيت والتحديث",
        "hijri-install-desc": "قم بتوزيع السكربت مباشرة باستخدام هذا الأمر:",
        "hijri-update-warn": "<strong>⚠️ خطوة تحديث هامة:</strong> إذا كنت تقوم بالترقية من إصدار أقدم، <b>يجب</b> مسح ملف التخزين المؤقت القديم لتطبيق التنسيق الجديد:<br><br><code>rm ~/.cache/waybar_hijri_cache.json</code>",
        "hijri-waybar-title": "🖥️ إعدادات Waybar",
        "hijri-waybar-desc": "أضف التالي إلى ملف <code>config.jsonc</code> الخاص بك (قم بتغيير معامل اللغة حسب رغبتك):",
        "hijri-style-title": "🎨 المظهر (الثيمات)",
        "hijri-style-desc": "اختر الثيم المفضل لديك وأضفه إلى ملف <code>style.css</code> الخاص بـ Waybar:",
        "hijri-theme-1": "1. Catppuccin (Mocha)",
        "hijri-theme-2": "2. Dracula",
        "hijri-theme-3": "3. Nord",
        "hijri-theme-4": "4. Gruvbox",
        "hijri-theme-5": "5. Tokyo Night",
        "hijri-perf-tip": "<strong>💡 نصيحة للأداء:</strong> يقوم السكربت بحفظ الشهر كاملاً في <code>~/.cache/waybar_hijri_cache.json</code>. إنه يجري مكالمة API واحدة فقط شهرياً!",
        "hijri-btn-repo": "عرض المستودع على GitHub",
        "hijri-footer-text": "© 2026 أحمد x86 • تم التطوير لمجتمع لينكس ❄️",
        
        // === Wallpapers Page Translations (AR) ===
        "wall-page-title": "أحمد x86 - معرض الخلفيات 🖼️",
        "wall-page-desc": "مجموعة منتقاة من خلفيات 4K البسيطة والجمالية المناسبة تمامًا لتخصيص لينكس وإعدادات Arch Linux و Hyprland.",
        "wall-col-title": "مجموعتي",
        "wall-col-desc": "إليك بعض من خلفياتي المفضلة المستخدمة في إعدادات Arch Linux المخصصة الخاصة بي. اضغط على أي صورة لعرضها بالدقة الكاملة.",
        "wall-page-4-desc": "الصفحة 4 - مجموعتي المختارة من خلفيات Reddit المخصصة لتوزيعات لينكس.",
        "wall-col-4-title": "مجموعتي (الجزء 4)",
        "wall-col-4-desc": "إليك بعض من أفضل الخلفيات المأخوذة من Reddit لإعدادات Arch Linux الخاصة بي. اضغط على أي صورة لعرضها بالدقة الكاملة.",
        "wall-page-5-desc": "الصفحة 5 - خلفيات ملكية مباشرة من ملفات إعداد Hyprland الخاصة بي.",
        "wall-col-5-title": "مجموعتي (الجزء 5)",
        "wall-col-5-desc": "إليك الخلفيات الملكية الجديدة من ملفات إعداد Hyprland. اضغط على أي صورة لعرضها بالدقة الكاملة.",
        "wall-page-6-desc": "الصفحة 6 - خلفيات سايبربانك، مطر نيون، وسيارات 4K من إعدادات Arch Linux الخاصة بي.",
        "wall-col-6-title": "مجموعتي (الجزء 6)",
        "wall-col-6-desc": "إليك الدفعة التالية من خلفيات ملفات إعداد Hyprland. اضغط على أي صورة لعرضها بالدقة الكاملة.",
        "wall-page-7-desc": "الصفحة 7 - الجزء الأخير من مجموعتي المختارة لإعدادات Arch Linux.",
        "wall-col-7-title": "مجموعتي (الجزء 7)",
        "wall-col-7-desc": "إليك الخلفيات الأخيرة المتبقية من إعدادات Arch Linux الخاصة بي. اضغط على أي صورة لعرضها بالدقة الكاملة.",
    }
};

let currentLang = localStorage.getItem('siteLang') || 'en';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('siteLang', lang); 

    if (lang === 'ar') {
        document.documentElement.setAttribute('dir', 'rtl');
        document.documentElement.setAttribute('lang', 'ar');
    } else {
        document.documentElement.setAttribute('dir', 'ltr');
        document.documentElement.setAttribute('lang', 'en');
    }

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            // التحقق مما إذا كان العنصر حقل إدخال لتغيير الـ placeholder بدلاً من الـ innerHTML
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.setAttribute('placeholder', translations[lang][key]);
            } else {
                el.innerHTML = translations[lang][key]; 
            }
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    setLanguage(currentLang);
});
